# Generated by Django 4.0.1 on 2022-06-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contatos_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='telefone',
            new_name='telefone1',
        ),
    ]
