# Generated by Django 4.0.1 on 2022-06-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contato_ddd2_contato_ddd3_contato_telefone2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contato',
            name='cep',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contato',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contato',
            name='estado',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='contato',
            name='rua',
            field=models.CharField(default='', max_length=200),
        ),
    ]
