# Generated by Django 4.0.1 on 2022-06-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contato_bairro_contato_cep_contato_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='ddd2',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='ddd3',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone2',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone3',
        ),
    ]
