# Generated by Django 4.0.1 on 2022-06-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contato_bairro_remove_contato_cep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='telefone1',
            new_name='telefone',
        ),
    ]
